services:
  # Main API service
  - type: web
    name: agenthub-registry-api
    env: python
    region: oregon
    plan: standard
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app -k uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT --workers 4 --worker-connections 1000 --max-requests 1000 --max-requests-jitter 50 --preload --timeout 120
    healthCheckPath: /health
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: LOG_LEVEL
        value: INFO
      - key: API_V1_STR
        value: /api/v1
      - key: PROJECT_NAME
        value: AgentHub Registry
      - key: PROJECT_DESCRIPTION
        value: Universal package registry for AI-native agents, tools, chains, and prompts
      - key: VERSION
        value: "1.0.0"
      - key: DATABASE_POOL_SIZE
        value: "20"
      - key: DATABASE_MAX_OVERFLOW
        value: "30"
      - key: REDIS_CACHE_TTL
        value: "3600"
      - key: MAX_PACKAGE_SIZE_MB
        value: "100"
      - key: RATE_LIMIT_PER_MINUTE
        value: "100"
      - key: SEARCH_RESULTS_PER_PAGE
        value: "20"
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: "11520" # 8 days
      - key: REFRESH_TOKEN_EXPIRE_MINUTES
        value: "43200" # 30 days
      - key: ANALYTICS_ENABLED
        value: "true"
      - key: VALIDATE_PACKAGE_SCHEMAS
        value: "true"
      - key: ENABLE_VIRUS_SCANNING
        value: "true"
      - key: ENABLE_VULNERABILITY_SCANNING
        value: "true"
      - key: ENABLE_PACKAGE_DELETION
        value: "false"
      - key: ENABLE_PRIVATE_PACKAGES
        value: "false"
      - key: ALLOWED_HOSTS
        value: registry.agenthubcli.com,agenthub-registry-api.onrender.com

      # Database connection (PostgreSQL)
      - key: DATABASE_URL
        fromDatabase:
          name: agenthub-registry-db
          property: connectionString

      # Redis connection
      - key: REDIS_URL
        fromService:
          type: redis
          name: agenthub-registry-redis
          property: connectionString

      # AWS S3 configuration (set these manually)
      - key: AWS_REGION
        value: us-east-1
      - key: S3_BUCKET_NAME
        sync: false # Set manually in Render dashboard
      - key: AWS_ACCESS_KEY_ID
        sync: false # Set manually in Render dashboard
      - key: AWS_SECRET_ACCESS_KEY
        sync: false # Set manually in Render dashboard

      # GitHub OAuth (set these manually)
      - key: GITHUB_CLIENT_ID
        sync: false # Set manually in Render dashboard
      - key: GITHUB_CLIENT_SECRET
        sync: false # Set manually in Render dashboard
      - key: GITHUB_OAUTH_REDIRECT_URI
        value: https://registry.agenthubcli.com/api/v1/auth/github/callback

      # Security (set these manually)
      - key: SECRET_KEY
        generateValue: true
      - key: SENTRY_DSN
        sync: false # Set manually in Render dashboard (optional)

  # Redis service
  - type: redis
    name: agenthub-registry-redis
    region: oregon
    plan: starter
    maxmemoryPolicy: allkeys-lru

# PostgreSQL database
databases:
  - name: agenthub-registry-db
    region: oregon
    plan: starter
    databaseName: agenthub_registry
    user: agenthub_registry_user
